### PR TITLE
Remove podman-compose dependency

### PR DESCRIPTION
**Pull request by chaitanyaenr**
We are not using it in the krkn code base. Also, this fixes one of the license issues reported by FOSSA.

### CODE REVIEW

**Comment by paigerube14** [comment]
Let's remove this file as well as it wont work without docker/podman-compose and isnt used: https://github.com/krkn-chaos/krkn/blob/main/docker-compose.yml

**Comment by paigerube14** [comment]
@chaitanyaenr taking a look at how to fix the failed docker build run here

**Comment by chaitanyaenr** [comment]
> Let's remove this file as well as it wont work without docker/podman-compose and isnt used: https://github.com/krkn-chaos/krkn/blob/main/docker-compose.yml

Done!

**Review by paigerube14 — APPROVED** [review]
/lgtm

**Pull request merged**
