### PR TITLE
separating build and test workflows

### PR DESCRIPTION
**Pull request by paigerube14**
Want to separate out the workflows to run build separately when pushes happen to main 

Q: Do we need to run test coverage after it is merged?

### CODE REVIEW

**Comment by chaitanyaenr** [comment]
@paigerube14 I don't think we need test coverage post merge given that we run them pre-merge.

**Comment by paigerube14** [comment]
@chaitanyaenr I updated the build.yml to only run on a pull-request. Think we might want with push on non main branches? 
I think what we have what you described in docker-image file. Or should I create a separate one for checking out main code only?

**Comment by paigerube14** [comment]
Ravi, does this pr look ok? See the 2 checks in the pr that were ran separately

**Review by chaitanyaenr — APPROVED** [review]
LGTM

**Pull request merged**
